services:
  redis:
    image: redis:7-alpine
    container_name: smartcheckout-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - smartcheckout-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: smartcheckout-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - smartcheckout-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  smartcheckout-network:
    driver: bridge
    name: smartcheckout-network
    external: false

volumes:
  redis-data:
    name: smartcheckout-redis-data
  rabbitmq-data:
    name: smartcheckout-rabbitmq-data

